### ISSUE TITLE
Minimum stability violation

### ISSUE THREAD

**Issue by sonofliberty** [Jorijn/bitcoin-bolt11#5]
Hi, thanks for your recent update. I'm running into a new problem however:
```
jorijn/bitcoin-bolt11 v0.2.0 requires protonlabs/bitcoin 1.0.x-dev -> found protonlabs/bitcoin[1.0.x-dev] but it does not match your minimum-stability.
```

Could you possibly replace "1.0.x-dev" with a stable version in composer.json?

**Comment by Jorijn** [comment]
From a quick glance: v1.0.4 in the `protonlabs/bitcoin` repository doesn't contain the necessary PHP 8.0 changes and v1.0.5 hasn't been tagged.

I haven't looked into it any further. You might be able to fix it on your end or you could try opening an issue over at Protonlabs to see if they could update the package's version. If you have any other idea I'd be happy to implement :)

**Comment by sonofliberty** [comment]
Ahh that's annoying. 😆 

Ok, I will have to deal with this in the meantime.

Thanks!

**Comment by Jorijn** [comment]
Just an update on my end: There hasn't been any progress in the Bit-Wasp repository regarding PHP 8 compatibility. I'll keep occasionally monitoring this and will eventually revert to the upstream repository. For now, I'll close this issue.
