### ISSUE TITLE
Breez Wallet PaymentRequests throw a SignatureDoesNotMatchPayeePubkey('lightning payment request signature pubkey does not match payee pubkey') exception.

### ISSUE THREAD

**Issue by bassim** [Jorijn/bitcoin-bolt11#6]
They decode fine, but checking against pubKey fails.
[lib/jorijn/bitcoin-bolt11/src/Encoder/PaymentRequestDecoder.php:390](https://github.com/Jorijn/bitcoin-bolt11/blob/master/src/Encoder/PaymentRequestDecoder.php#L390)

for example:

lnbc2500u1p3gh9gcpp5rdcwr3hgguv04se3r2u8aucsd7uzjgysh6ffnf485q27nd39cywsdq8vfkrxuqcqzpgxqrrssrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwqqqqqyqqqqqqqqqqqqlgqqqqqqgqjqnp4q0zukujkjax39vxqz2fracvwxs4zrv72xtc3k3lck920ah3z9ma9vsp5w2m93aylffc8ysnv8nnu0pws4ly97txhreta9pxt5e4zj7x3d96q9qyyssqlg36ek8jx8mwfgm6crgpv6qh2xz9h9ga0wf2rqmy3lpvdhdd6p8s42e4s4f2yjazr3lw7m275y3kglrpr046wwqv3jwf8znh96wzl2cp0cvq2c

**Comment by bassim** [comment]
We noticed that it depends on the amount of your withdrawal. This in turn depends on the amount sats that you have deposited in the past. See for example this screenshot, if you withdraw an amount lower than 15540 sats decoding works fine, above 15540 sats it breaks. Temp. solution for me would be to deposit sats to increase that 15540 threshold so a higher withdraw can be decoded. 
![Screenshot from 2022-05-25 14-35-22](https://user-images.githubusercontent.com/748403/170264540-1bbf0d4f-df89-4e08-912f-1fa221d98f52.png)
.

**Comment by Jorijn** [comment]
Hey @bassim 

I just pushed a bug fix related to deriving the payee public key. PR #7 should fix this. I've asked the reporting party to test it before I'm going to merge it, but I'm pretty certain this should fix your issue as well.

**Comment by bassim** [comment]
Hi Jorijn, I just tested my issue on #7 and can confirm that it also fixes this issue! Closing, Thanks!

**Comment by Jorijn** [comment]
Great, thanks for testing! I'll release a new version today.
